### ISSUE TITLE
Missing a few verbalized words

### ISSUE THREAD

**Issue by ghost** [Lyroxide/yomichan-korean#1]
The new dictionary is missing a few verbalizations that the old dictionary was capable of detecting...

It seems like it is lacking a few endings like 운 and 는 while being used with a verb, the old KR-DICT didn't seem to have problem finding those words

무서운

![image](https://github.com/Lyroxide/yomichan-korean/assets/103891807/9938fb3e-f7df-4183-aaa1-8dab323224ca)

[계속 우는 소리] "우는"

![image](https://github.com/Lyroxide/yomichan-korean/assets/103891807/4931a6bb-1325-4744-8038-dab001cbdce5)

호랑이는 소를 먹고 싶은데 갑자기 시끄러운 아기 울음소리를 들었다. "시끄러운"

![image](https://github.com/Lyroxide/yomichan-korean/assets/103891807/3775fc56-4edb-49c2-ae3a-78421d587385)

By the way, i just wanted to add a comment about what amazing work you have done with this dictionary, and also in the future if you can add a frequency list with numbers rather than stars.

Like this

![image](https://github.com/Lyroxide/yomichan-korean/assets/103891807/1538a924-7a2f-43c2-ae7c-3692c387aac1)

**Comment by Lyroxide** [comment]
@RyanOrigens Thank you for reporting the mistakes. I have completed misunderstood how ㅂ and ㄹ irregulars work. I will push a commit soon.

As for the frequency dictionary, it is currently out of my league. The stars are from the KRDICT itself, which is a "Learner's" dictionary, hence the existence of stars to help learners how frequent the words are. Other dictionaries like the monolingual STDICT and OPENDICT won't have them.

**Comment by Lyroxide** [comment]
@RyanOrigens Also could you link me to a reliable source where ㄹ is dropped when conjugating 는? KoParadigm conjugated 울다 as 울는 so I'm slightly confused.

**Comment by ghost** [comment]
The one i use is this one "https://www.verbix.com/" But, how my korean level is actually pretty bad i cannot know for certain whether it is a good one or not.

you should try to use both dictionaries at the same time, maily the english version and try to find partners where your dictionary cannot recognize and the old one could, i'm finding a few words/verbs that aren't those ones that also weren't recognized.
