### ISSUE TITLE
Replacing Dictionaries explanations with tatoeba example sentence.

### ISSUE THREAD

**Issue by ghost** [Lyroxide/yomichan-korean#15]
The example sentences that come with KR-dict are not actually good; they are only explanations and don't utilize the target word. It would be nice if you could replace them with Tatoeba example sentences for something closer to the [Jitendex](https://github.com/stephenmk/Jitendex) dictionary for Japanese.

**Comment by Lyroxide** [comment]
Hmm, yeah. I initially only put the first 3 examples, which are all useless. I have reformated the dictionary such that all examples from krdict are included then you can use CSS to only show the last few examples, which are more useful (I think)

![image](https://github.com/Lyroxide/yomichan-korean/assets/33834537/bc878e7a-c2b3-40b9-a7ba-aa0e0a04ce7b)

Would you rather see these last few examples, than the first few?

Also, I cannot find examples of this word on Tatoeba

**Comment by ghost** [comment]
Sorry for the delay; I've been extremely busy and couldn't find the time to answer.

I believe the issue lies with the dictionary itself; the example sentences provided aren't actually examples but rather explanations, and many of the definitions are repetitive or says non-equivalent expressions.

I've been exploring a couple of different dictionaries and ended up stumbling across three that caught my attention.

You could try properly formatting those dictionaries; they seem to have potential in my opinion.

Take a look at them:

https://drive.proton.me/urls/3RY82EBQ2M#s7QNTK6lZKtZ

https://github.com/MarvNC/yomichan-dictionaries?tab=readme-ov-file#other-1 [Ligoes Vicom]

Mainly from the "Kedict" dictionary, you should be able to find some decent data. It includes example sentences.

![image](https://github.com/Lyroxide/yomichan-korean/assets/103891807/0ec6ab03-4565-4b8a-9a4b-d3d53672bd13)

Or you could try to utilize the data from Vicon Kor to Eng and add one or two example sentences per sense from Tatoeba.

I don't know what their licensing is, though.

**Comment by ghost** [comment]
Update:

I've seen by your screenshot and seem like your dict is actually example sentences rather than only an explanation, have you updated the dictionary on google drive?

In regards to your question about whether I would prefer to see the last examples rather than the first one, my level of Korean is really bad for judging example sentences, and since this is a screenshot, I cannot translate it.

**Comment by Lyroxide** [comment]
New versions of krdict and stdict will be released in tandem with the Korean update in Yomitan, which will come soon

I will release these dictionaries as is without additional information from other sources. I just don't want to tamper the original dictionary.

I might look into Lingoes Vicon to increase coverage. Thanks.
