### ISSUE TITLE
Incomplete quick-action popup

### ISSUE THREAD

**Issue by momoongithub** [Lyroxide/yomichan-korean#16]
**Description**
Thank you so much for sharing the tool!!! I think it’s really helpful for my language learning.Everything goes well, except for an insignificant problem:The display of quick-action popup is incomplete like this.
![Snip20240430_19](https://github.com/Lyroxide/yomichan-korean/assets/165360662/39d7fd2f-9be9-4326-989d-729c36f6913f)

**Browser version**
Chrome 124.0.6367.92

**Yomichan version**
V1.2

**Comment by Lyroxide** [comment]
Integration of Korean into Yomitan (where this bug is fixed) is currently ongoing. Wait for a few weeks. Thanks.

**Comment by momoongithub** [comment]
That sounds good!Thank you for your reply!

**Comment by Lyroxide** [comment]
Korean is now in Yomitan

**Comment by momoongithub** [comment]
Now it can be fully displayed.Thank you so much!!!
