### ISSUE TITLE
Term in Dictionary Form

### ISSUE THREAD

**Issue by momoongithub** [Lyroxide/yomichan-korean#17]
I encounter a problem in creating Anki flashcard: I need the term that has been reduced to dictionary form by Yomitan, but I can’t find the accurate marker.For example, in this case I need the term "웃다". When I choose {cloze-body}, it shows "웃으며". When I choose {expression}, it shows "욷따". When I choose {selection-text}, it shows "웃으며". None of them is what I need.😭
![Snip20240613_1](https://github.com/Lyroxide/yomichan-korean/assets/165360662/e17cd04f-f1d7-425a-9004-f3b08259d072)

**Comment by Lyroxide** [comment]
I am sure that  {expression} will give you what you want. Can you reset templates in Configure Anki card templates and try again?

**Comment by momoongithub** [comment]
I reset Anki card templates but it didn't work.Then I updated Yomitan to the latest version(24.6.3.0) and reset almost all settings, still “욷따”!😩

**Comment by Lyroxide** [comment]
Can you export and upload your Yomitan settings and Anki deck?

**Comment by momoongithub** [comment]
https://drive.google.com/drive/folders/19PMRh6OjKRRcHrBhfBTGxn2TQsM7Dbzh?usp=sharing

**Comment by Lyroxide** [comment]
Please only use the bigger green button to add cards.

**Comment by momoongithub** [comment]
Oh my god, I just realized that the shortcut action I set is "add term note(reading)". Now I can finally get the term "웃다". Thank you soooooo much for your patient guidance!!!🥰
