### ISSUE TITLE
A Pronunciation Discrepancy: Comparing KRDICT and Naver for 흩어지다

### ISSUE THREAD

**Issue by huannv100** [Lyroxide/yomichan-korean#3]
I just noticed a discrepancy between the pronunciation of 흩어지다 in KRDICT (Yomichan) and Naver's dictionary. In my opinion, the Naver dictionary seems to be correct in this instance. Could this be a simple typo, or is it a systematic mistake in the dictionary?

KRDICT (Yomichan): 흩어지다 [ 흐서지다]
Naver dictionary: 흩어지다 [ 흐터지다 ]
KRDICT website: 흩어지다 [ 흐터지다 ]

![image](https://github.com/Lyroxide/yomichan-korean/assets/49158530/b78365d1-2578-4ebd-9842-d68366b510c6)

**Comment by Lyroxide** [comment]
흐터지다 is indeed the correct reading. Thanks for pointing it out. KRDICT has been updated in the drive, please check it out.

**Comment by huannv100** [comment]
I noticed that you updated it for KR-EN but not for other dictionaries. Was this a mistake limited to this word only, or have there been many similar ones that were corrected? I ask because I use Yomichan on around 5 different devices, so if it's just one word, I probably don't need to update it.

**Comment by Lyroxide** [comment]
It probably affected many words too, since previously the readings were automatically generated. I have updated it for all three KRDICT by scraping the correct pronunciation from the website. Sorry for the inconvenience, but the dictionaries will receive regular updates if I find new ways to improve the lookup function.

**Comment by huannv100** [comment]
Thank you.
It's good that you keep improving them. I think it's probably the best one now, except that you cannot look up phrases. Naver probably did that mostly in their open dictionaries.
