### ISSUE TITLE
[Feature Request] Enabling Whole Phrase Searches

### ISSUE THREAD

**Issue by huannv100** [Lyroxide/yomichan-korean#4]
Unlike Naver, KRDICT doesn't currently support entering a whole phrase to look up words. For instance, if you want to understand the meaning of "입이 무겁다", you can't input the entire phrase into the search box on KRDICT to get the result directly. However, in Naver dictionary, you can do this as shown in the link below:

https://en.dict.naver.com/#/search?query=%EC%9E%85%EC%9D%B4%20%EB%AC%B4%EA%B2%81%EB%8B%A4&range=all

Feature Request: Could you consider adding an option that allows users to select a phrase, whether conjugated or not, and consult the Naver dictionary for more information?

**Comment by Lyroxide** [comment]
The point of Yomichan is to remove the need to look up words online. It is thus my job to create dictionaries that contain enough coverage. However, neither KRDICT, nor STDICT/OpenDICT have 입이 무겁다 as their headword. I understand that this is annoying, but what I have scraped are what I can put in the dictionaries. Naver however is not scrapable (I don't even know the source of my Japanese Naver).

You can always select the characters and look them up in your favourite search engine like Google. I'm not sure how is that any different from using Naver.

**Comment by huannv100** [comment]
When I set the scan modifier key to "No key" on mobile, every time I select a word, it opens the popup window, and I don't see any way to copy it to look it up on a page. Do you know how to do it? Additionally, it would be great to have the option to prevent the popup from opening when the selected text is a link or hyperlink. 
It would be much more convenient if there was a way to copy the selected text and have it automatically open the lookup on Naver dictionary directly. While accomplishing this is simple on Windows using AHK or other methods, I'm not sure how to do it on mobile devices.

**Comment by Lyroxide** [comment]
OK I get what you mean. I'll look into it

**Comment by Lyroxide** [comment]
@huannv100 I've got a workaround. In the second 'Scanning Inputs',
Input Types: Touch, Pen
Search types: Search for terms
Touch options: Scan on touch release, Prevent touch scrolling
Pen options: Scan on pen release, Prevent pen scrolling

If you want to select a word to copy, scan a word first, then tap and hold a blank space without any text. The pop-up should remain, but you can tap and hold any text now to copy. This works on my phone.

**Comment by huannv100** [comment]
Somehow, it just doesn't really work for me. It works maybe once or twice out of 100 attempts.

**Comment by huannv100** [comment]
Do you know where I can find the source code for scraping KRDICT? I want to do something similar, but for KR-some language other than English.
