### ISSUE TITLE
Verbs Not Working in Yandex Browser with Protect

### ISSUE THREAD

**Issue by huannv100** [Lyroxide/yomichan-korean#5]
I installed the extension on Yandex Browser with Protect, but I've run into a problem. It seems to work fine with nouns, but when it comes to verbs, nothing happens when I click on them. I'm not sure what could be causing this issue. Any insights into the possible cause?

**Comment by Lyroxide** [comment]
That probably means Yandex cannot support the new hangul.js package. Use Kiwi instead
