### ISSUE TITLE
Merge into Yomitan

### ISSUE THREAD

**Issue by dgisser** [Lyroxide/yomichan-korean#6]
As you mention in the readme, yomitan is the de facto fork for yomichan. Any plans to try to submit a PR to yomitan to merge korean in? I realize it wouldn't merge cleanly in the current state, if you need coding help I'm happy to chip in.

**Comment by Lyroxide** [comment]
I have my own qualms doing this at the moment since it interferes with Japanese lookups (time taken, deconjugation, dictionary support). Also, Yomitan is focused on implementing Manifest V3 support.

**Comment by dgisser** [comment]
I feel confident that we could address some of these issues (time taken/deconjugation should be doable since korean occupies a different space in utf than any other language, unless the dictionary includes both 한글 and 한자). Maybe it wouldn't hurt to rebase the repo on top of yomitan, work on making sure it doesn't disrupt anything important, and if it gets to a good state submitting a PR for the maintainers to decide? You can message me on the yomitan discord as well.
