### ISSUE TITLE
Trouble downloading the extension (noob)

### ISSUE THREAD

**Issue by mimi-icl** [Lyroxide/yomichan-korean#9]
Hi, I followed the instructions and downloaded the Releases 1.2V for Chrome and unzipped it. I'm not quite sure where to go from here. There are quite a few json files in the folder and I'm not sure if I should just import all of them to yomichan or not. Is it possible to get more detailed instructions for us noobs that have never done this before? :)

**Comment by Lyroxide** [comment]
No worries.

1. Download yomichan-korean-chrome.zip from Releases
2. Assuming you have 7-zip installed, right click on the zip and select 7-Zip > Extract to 'yomichan-korean-chrome\'. The manual way would be creating a folder anywhere, named as anything, and extract everything from the zip to the folder. This is how it should look like when you open the folder.
![explorer_usEj08fLzT](https://github.com/Lyroxide/yomichan-korean/assets/33834537/98e3a6fe-afd8-4dfc-8e4c-068e745bda72)

3. Go to chrome://extensions/ on Chrome. 
4. Click on 'Load Unpacked'.
5. Select the yomichan-korean-chrome folder (NOT the folders inside) and click 'Select Folder'. Welcome page should appear automatically.
6. Download dictionaries from the README. Do NOT extract them.
7. Go to Yomichan settings. Under Dictionaries > Configure installed and enabled dictionaries..., click 'Import'.
8. Select the downloaded dictionaries in zip.

**Comment by mimi-icl** [comment]
I got it downloaded, tysm! Though I noticed the dictionary can't recognise words like 많은. It recognises the 은 but not the 많. Is this one of the deinflection idiosyncracies you mentioned in the README or did I just mess up haha?

**Comment by Lyroxide** [comment]
What dictionary did you download?

![vivaldi_Ek3ZD4bYZC](https://github.com/Lyroxide/yomichan-korean/assets/33834537/c987f12c-6066-478e-9fb6-ef788924362d)
